tuple1=('a','b','c','d','e')
tuple2=(3,304,"Hello")
print(tuple1)
print(tuple2)
print("1.Creating tuple")
tuple3=("BASU")
print(tuple3)
print("2.Repetation")
tuple3=tuple2*2
print(tuple3)
print("3.Concatination")
tuple3=tuple1+tuple2
print(tuple3)
print("4.Range Slicing")
tuple3=tuple1[0:4]
print(tuple3)
print("5. Slicing")
tuple3=tuple2[2]
print(tuple3)
print("6.String Membership")
tuple3='h' in tuple1
print(tuple3)
print("7.length")
tuple3=len(tuple1)
print(tuple3)
print("8.Maximum")
tuple3=max(tuple1)
print(tuple3)
print("9.Access")
print(tuple1[2])
print("10.Data TYpe")
print(type(tuple1))
